### ISSUE TITLE
Game doesnt gives you the rest of the starter pistols

### ISSUE THREAD

**Issue by JustAdoomer** [Sumwunn/uccfn-gzcp#1]
upon started a game the game doesnt give you the plasma pistol (the one that works similar to doom 2016 pistol) and the demon tech pistol also default pistol doesnt have a ammo counter of what you have in the mag for some reason
![Screenshot_Doom_20211007_192313](https://user-images.githubusercontent.com/92126371/136470436-d21e084a-93fc-4913-942d-d79515415265.png)

**Comment by JustAdoomer** [comment]
i noticed when giving all the weapons is that the also the pistol without a mag counter is the wrong version of the same gun since when using give all command it gives me the correct pistol

**Comment by Sumwunn** [comment]
How does your load order look?

**Comment by JustAdoomer** [comment]
![Captura de pantalla (338)](https://user-images.githubusercontent.com/92126371/136474118-769e6523-dc94-4c66-9d10-1c43fa2b8dce.png)

**Comment by JustAdoomer** [comment]
by the way i also noticed the slot 6 weapons order is like very wrong compared to the default slot 6 weapons nexus order

**Comment by Sumwunn** [comment]
Load order looks ok (textcolours should be on the bottom, and insanelca should be v1.3a, but they do not appear to be the cause). I'm not having any luck reproducing this.

What version of GZDoom are you using?

**Comment by JustAdoomer** [comment]
as for now im using gzdoom gles 4.6.1(gles means that this gzdoom variant just has a different opengl renderer implevemented optionally)

**Comment by Sumwunn** [comment]
4.6.1 in GLES gave me some crashes; however, no HUD issue.

Are you able to try 4.7.0?

EDIT: No GLES crashes in 4.7.0.

**Comment by JustAdoomer** [comment]
alright imma test it

**Comment by JustAdoomer** [comment]
also the wrong pistol problem thing seems to get resolved in lzdoom

**Comment by JustAdoomer** [comment]
i tested it with gzdoom 4.7.0 it doesnt seem to work (about the pistol begin wrong version) unless i chose the "random" class it seems it also resolves the minor problem of the hud latters begin the wrong color (btw i also selected random class in lzdoom idk why theres like 7 copys of "doom guy" class in there)

**Comment by Sumwunn** [comment]
Random class? Huh. Sounds like another mod is autoloading along with everything else. I do not believe there are any classes in CF. Could you post a screenshot of the classes?

You may have luck creating a fresh GZDoom folder.

**Comment by JustAdoomer** [comment]
![Captura de pantalla (339)](https://user-images.githubusercontent.com/92126371/136478501-ab54e6c8-ba3a-45ac-a69e-0cd375bb87c8.png)

**Comment by Sumwunn** [comment]
Yeah, something else is going on for sure. I'd definitely try a fresh GZDoom folder.

**Comment by JustAdoomer** [comment]
there isnt any mod that autoloads when i play gzdoom without the mod as far i know since theres aint any autoload files of any sort in the files

**Comment by Sumwunn** [comment]
Hmm. No skins folder either?

**Comment by JustAdoomer** [comment]
nop

**Comment by Sumwunn** [comment]
Are you able to scroll back up to the top of GZDoom's console to make sure?

**Comment by Sumwunn** [comment]
Should show everything that has loaded.

**Comment by JustAdoomer** [comment]
alright

**Comment by JustAdoomer** [comment]
besides of the addons i have used for a bit to play along with the single map(which doesnt adds any classes since they are universal) im using rn there isnt any unknown or strange file loading the only things that loads first is gzdoom.pk3 and game_support.pk3 doom2.wad game_widescreen_gfx.pk3

**Comment by JustAdoomer** [comment]
also i tested before the hellfire cyberdemon his like nuke death smoke before turning into hellfire cardinal seems to be way too slow to disappear than the rest of the nuke smokes of other things idk if thats a issue with the original mod or the patch

**Comment by Sumwunn** [comment]
"(which doesnt adds any classes since they are universal)"

Could you elaborate?

**Comment by JustAdoomer** [comment]
i mean like addons that only adds minor shaders thing like boosting bloom motion blur vignette and some addons like gearbox universal enhanced ai tactical lean nashgore damage numbers and livereverb

**Comment by Sumwunn** [comment]
You're loading those with CF?

**Comment by JustAdoomer** [comment]
like loading them first and then cf along with the patch

**Comment by Sumwunn** [comment]
I wouldn't load any other mods with CF, as CF changes almost everything.

I assume you tried CF without addons?

**Comment by JustAdoomer** [comment]
yes

**Comment by Sumwunn** [comment]
Did CF work OK without those addons? I'm just a little confused, sorry.

**Comment by JustAdoomer** [comment]
yeah did cf work okey it just still had the weird classes issue along with cf trying execute console commands by default

**Comment by JustAdoomer** [comment]
okey removing my ini did resolve the weird class issue

**Comment by Sumwunn** [comment]
The console commands message is normal as GZDoom doesn't allow mods to execute console commands from ACS scripts, but that shouldn't hurt anything.

About your classes, I have no idea.

**Comment by Sumwunn** [comment]
Oh, nice!

**Comment by JustAdoomer** [comment]
i think my ini file somehow contained some data that maybe could be related to mods adding classes like hideous destructor or brutal doom or something else that made gzdoom think cf has classes

**Comment by JustAdoomer** [comment]
i remember having a similar issue to some versions of brutal doom v20 like repeated classes or something like that

**Comment by Sumwunn** [comment]
Ah, I see. Welp, I'm glad you were able to solve it.

I would recommend keeping separate INI's for large mods (such as CF).

**Comment by JustAdoomer** [comment]
alright
